USE [master]
GO

/****** Object:  Database [DRSDATA_2015]    Script Date: 2015/3/15 13:15:19 ******/
CREATE DATABASE [DRSDATA_2015]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DRSDATA_2015', FILENAME = N'D:\DATA2015\DRSDATA_2015.mdf' , SIZE = 3060736KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DRSDATA_2015_log', FILENAME = N'D:\DATA2015\DRSDATA_2015_log.ldf' , SIZE = 4096KB , MAXSIZE = 2048GB , FILEGROWTH = 1%)
GO

ALTER DATABASE [DRSDATA_2015] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DRSDATA_2015].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DRSDATA_2015] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET ARITHABORT OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DRSDATA_2015] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DRSDATA_2015] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DRSDATA_2015] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DRSDATA_2015] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DRSDATA_2015] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET RECOVERY FULL 
GO

ALTER DATABASE [DRSDATA_2015] SET  MULTI_USER 
GO

ALTER DATABASE [DRSDATA_2015] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DRSDATA_2015] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DRSDATA_2015] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DRSDATA_2015] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DRSDATA_2015] SET  READ_WRITE 
GO


